### ISSUE TITLE
Terminate batch job exits with n or N

### ISSUE THREAD

**Issue by peterennis** [ionic-team/stencil-app-starter#11]
The system also shows multiple prompts when using Ctrl-C

![capture176](https://user-images.githubusercontent.com/140737/30842227-ad3ac9f6-a235-11e7-83d7-9d684c70e4bb.png)

![capture179](https://user-images.githubusercontent.com/140737/30842530-a790c9b8-a237-11e7-89cf-f9ad00eaafe0.png)

**Comment by jgw96** [comment]
This issue was moved to ionic-team/stencil-utils#1

**Comment by jgw96** [comment]
Hello because this is related to the `stencil-utils` and not this starter, I have moved this issue to that repo. Thanks!
