### ISSUE TITLE
Confusion with stencil-starter and stencil-component-starter

### ISSUE THREAD

**Issue by peterennis** [ionic-team/stencil-app-starter#12]
I have tried both and the difference is not clear.
Why are there two seemingly identical systems?

**Comment by siedentm** [comment]
@peterennis both are example projects for getting stared with stencil. one is for building components (and creating a distributable version), the other one is for creating complete apps with stencil (and consuming the distributable versions). I don't consider them to be identical. Both a built upon the same compiler so they are similar. So are many many of those 30k webpack based boilerplates. they do some things in a different manner but look very similar.

**Comment by peterennisrda** [comment]
That cleared it up for me. Thanks.
