### ISSUE TITLE
Bug template missing

### ISSUE THREAD

**Issue by peterennis** [ionic-team/stencil-app-starter#17]
Ref: https://github.com/ionic-team/stencil-component-starter/issues/16

![capture189](https://user-images.githubusercontent.com/140737/31110730-e4ff04aa-a7bd-11e7-8f9a-638eba317751.png)

**Comment by jgw96** [comment]
Thanks for opening an issue with us! Closed with https://github.com/ionic-team/stencil-app-starter/commit/4f96b8fd21a9cd839b282a8c0522ecccc67963c0
