### ISSUE TITLE
tsconfig.json seems to be unused

### ISSUE THREAD

**Issue by Evertt** [ionic-team/stencil-app-starter#23]
I tried to change some of the typescript configuration and noticed that nothing changed. So then I wondered if the config file was actually being used so I deleted it to see if that would generate any error and it didn't.

So yeah I wonder if that was your intention. Because I found it rather frustrating that I've been trying to change the typescript config for almost an hour, all for naught.

**Comment by kyr0** [comment]
+1 Ran into that as well ;)

**Comment by jgw96** [comment]
This functionality has been added in the latest release of Stencil 🎉 ! To update you can run `npm install @stencil/core@next --save-exact`. Thanks!
