### ISSUE TITLE
my-name vs. my-component

### ISSUE THREAD

**Issue by peterennisrda** [ionic-team/stencil-app-starter#25]
@mlynch,  stencil-component-starter made the change to use my-component instead of my-name.
https://github.com/ionic-team/stencil-component-starter/commit/5bfa95ab9e81cc27585c9b7d53af12ca8da11c69
It would then seem to make more sense for stencil-app-starter to use my-app-name (or my-appname)  instead of my-name.

**Comment by jgw96** [comment]
Hello! This was just fixed a minute a few minutes ago with a PR I merged. Thanks for opening an issue with us!
