### ISSUE TITLE
npm start any change will fail with Uncaught SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by mira-kovar** [ionic-team/stencil-app-starter#26]
```
@stencil/core@0.0.7-2 
```

**I'm submitting a ...**
[x] bug report

**Current behavior:**
When start project (clean clone) and install dependencies. Run `npm start` browser came up as expected, componnent is rendered as expected. Than when I modify file `my-name.tsx` terminal looks normally, browser refresh and file `www/build/app.js` will change where parametters `appCore` has value `undefined` same for parameter `appCorePolyfilled`. So live reload is usles, when i run `npm start` again build procces will succes, change in `my-name.tsx` will apear.

**Expected behavior:**
Livereload... output of page change...

**Steps to reproduce:**
modify `my-name.tsx` and hit save.

**Other information:**
Mac OS High Sierra, npm version 5.5.1.

**Comment by cary-smith** [comment]
Try setting the stencil @stencil/core version to 0.0.6? Does it work again?

**Comment by jgw96** [comment]
Hello! Thanks for using Ionic! This has since been fixed.
