### ISSUE TITLE
test.watch - Error: This promise must be present when running with -o

### ISSUE THREAD

**Issue by cary-smith** [ionic-team/stencil-app-starter#30]
**Stencil version:** (run `npm list @stencil/core` from a terminal/cmd prompt and paste output below):

```
@stencil/core@0.0.8-0
```

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
Cannot execute `npm run test.watch`

**Expected behavior:**
The ability to develop via TDD

**Steps to reproduce:**

1. Clone the `stencil-app-starter` repo
2. Run `npm i`
3. Run `npm run test.watch`

**Related code:**

```
// nothing new
```

**Other information:**

Just trying to get started in TDD and hit this wall. 😞 
This same problem is affecting the `stencil-component-starter` as well.

**Comment by jgw96** [comment]
Hello! Thanks for using Stencil. This issue has been fixed with the latest version of Stencil, 0.2.2. Thanks!
