### ISSUE TITLE
Cannot step into breakpoint in Visual Studio Code

### ISSUE THREAD

**Issue by michaelchu28** [ionic-team/stencil-app-starter#34]
**Resources:**
Before submitting an issue, please consult our [docs](https://stenciljs.com/).

**Stencil version:** (run `npm list @stencil/core` from a terminal/cmd prompt and paste output below):
@stencil/core@0.0.6-10
```
 insert the output from npm list @stencil/core here
```

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

I cannot step into breakpoint. When I hover over the breakpoint, I see message **"breakpoint ignored because generated code not found (source map problem?)".**

**Expected behavior:**

It should step into the breakpoint when I am in debug mode.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by jgw96** [comment]
Hello! Thanks for using Stencil! At this time we do not actually generate source maps in stencil builds, although we do plan on adding this https://github.com/ionic-team/stencil/issues/219.

**Comment by michaelchu28** [comment]
Ok thanks for letting me know.
