### ISSUE TITLE
Confused about getting started instructions

### ISSUE THREAD

**Issue by asunar** [ionic-team/stencil-app-starter#36]
**Stencil version:** (run `npm list @stencil/core` from a terminal/cmd prompt and paste output below):

```
$ npm list @stencil/core
@stencil/starter@0.0.1 C:\code\sandbox\my-app
`-- @stencil/core@0.1.1-0
```

**I'm submitting a ...**  (check one with "x")
[x ] bug report

**Current behavior:**
npm test fails with
> ● app-profile › rendering › should not render any content if there is not a match

1 test suite with 5 tests took 5.755secs to complete. 

> Test Suites: 1 failed, 2 passed, 3 total
> Tests:       2 failed, 3 passed, 5 total
> Snapshots:   0 total
> Time:        5.755s
> Ran all test suites.

The instructions at https://stenciljs.com/docs/getting-started refer to files that do not exist in the starter repo.
> Open src/components/my-name/my-name.tsx in your editor

**Expected behavior:**
All tests are expected pass.
Tests suite is expected to take much less time.
The files mentioned in the instructions are expected to be in the starter repo

**Steps to reproduce:**
Follow the instructions on https://stenciljs.com/docs/getting-started

**Comment by jgw96** [comment]
Hello! This is fixed with the latest version of Stencil 0.2.2, thanks!
