### ISSUE TITLE
Router link not working.

### ISSUE THREAD

**Issue by ZikZakJainy** [ionic-team/stencil-app-starter#37]
I just clone the master branch by using the following command
**`git clone https://github.com/ionic-team/stencil-app-starter my-app`** ,
 shown in the document and install npm and run the project by using npm start but 
**`<stencil-route-link url='/profile/stencil'>
          <button>
            Profile page
          </button>
</stencil-route-link>`**
this navigation button not working.

**Comment by jgw96** [comment]
Hello @ZikZakJainy , unfortunately, I cannot reproduce this issue. Are you getting an error in the console, any other info you can share?

**Comment by ZikZakJainy** [comment]
No actually, I am not getting any error in the console but when I am clicking on a button or any other router link so it's not redirecting to any other linked component. I just clone the project from Github repo, install npm and run the project, but It's not working.

**Comment by kyr0** [comment]
Cannot reproduce this either. In general, it works. Which browser do you use? Can u name the version of npm, tsc and node that you are using?

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue I will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Stencil!
