### ISSUE TITLE
matchPath is not defined.

### ISSUE THREAD

**Issue by ansarizafar** [ionic-team/stencil-app-starter#39]
I am getting this error with both stencil starter and ionic pwa tool kit.

![image](https://user-images.githubusercontent.com/5788284/36014413-78ee591c-0d8b-11e8-8124-17cffefb6a3a.png)

**Comment by jgw96** [comment]
Hello! With the latest release of the router (0.0.25) this is fixed (: To get the latest you can run `npm install @stencil/router@0.0.25 --save-exact`. Thanks for using Stencil!
