### ISSUE TITLE
Add SSR express server

### ISSUE THREAD

**Issue by mlynch** [ionic-team/stencil-app-starter#4]
Also might be nice to do a "one click" deploy to a service like Heroku for that SSR server

**Comment by mokupindia** [comment]
@mlynch - Nice work! appreciate and thank you to the entire team of Ionic to implement Stencil, much awaited looking forward to see it in action, in future rollout of Ionic. Good Luck.

Will the team also implement Redux?

Apologies as I know this is not the correct forum to add these lines :)

Cheers,
https://medium.com/@sunilk

**Comment by jgw96** [comment]
This has been added into a seperate starter https://github.com/ionic-team/stencil-ssr-starter
