### ISSUE TITLE
Tried to add <ion-tabs> in a bottom <ion-toolbar> but it's not showing up

### ISSUE THREAD

**Issue by kyr0** [ionic-team/stencil-app-starter#41]
Hi,

I just started playing around with Stencil and this app-starter. At first it seemed to me like all the Ionic framework components are already available -- but when I tried `<ion-tabs><ion-tab>` etc. pp. I realized that they actually don't show up.

Is this a bug? Is it intention?

If a web component is not available I would expect an error to be thrown and visible in the console that tells me about it. 
If a web component is not functional I would expect it not to be available already ;)

Or am I missing something? Do I need to do more than just using the tags?
I haven't seen any specific importing code for the web components used in the starter code so I expected them to be auto-available because of the core-dependency?

Thanks and best,
Aron

**Comment by jgw96** [comment]
Hello! To use Ionic components in this starter you need to install `@ionic/core`. To get a starter that already has this installed you can check out the Ionic PWA Toolkit! https://github.com/ionic-team/ionic-pwa-toolkit
