### ISSUE TITLE
Clean project gives blank page

### ISSUE THREAD

**Issue by goszczynskip** [ionic-team/stencil-app-starter#43]
**Stencil version:** 

```
@stencil/core@0.4.0
```

**I'm submitting a ...**
[x ] bug report

**Current behavior:**
After doing all steps in getting started section, I get blank page on http://localhost:3333/

**Expected behavior:**
I should get some demo layout/text

**Steps to reproduce:**
Follow steps included in guide.
```
git clone https://github.com/ionic-team/stencil-app-starter my-app
cd my-app
git remote rm origin
npm install
npm start
```

**Comment by joselee** [comment]
I have the same issue. Followed the quick start instructions @goszczynskip mentioned above, browser opens up to a blank page. No errors in browser console or in build command shell.

operating system: Windows 10
node: 6.11.0
npm: 3.10.10
stencil: 0.4.0

**Comment by jgw96** [comment]
Hello all! I just updated this starter to the latest release of Stencil which fixes this issue. Thanks for using Stencil!
