### ISSUE TITLE
running `npm list @stencil/core` gives unexpected result

### ISSUE THREAD

**Issue by franktopel** [ionic-team/stencil-app-starter#47]
Tested on Ubuntu 17.10.1 / zsh

**Stencil version:** (run `npm list @stencil/core` from a terminal/cmd prompt and paste output below):

```
@stencil/starter@0.0.1 /home/connexo/Sites/my-app
└── (empty)
```

**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
See above.

**Expected behavior:**
Outputs the version of stencil being used based on package.json.

**Steps to reproduce:**
Follow the readme-md's instruction on cloning, npm installling and starting the app starter.

**Related code:**
✘ connexo@connexo-HP-ZBook-15  ~/Sites/my-app   master ●  npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

up to date in 3.799s
 connexo@connexo-HP-ZBook-15 > ~/Sites/my-app - master ● > npm list @stencil/core~
@stencil/starter@0.0.1 /home/connexo/Sites/my-app
└── (empty)

 ✘ connexo@connexo-HP-ZBook-15 > ~/Sites/my-app - master ● > cat package.json|grep @stencil
  "name": "@stencil/starter",
    "@stencil/core": "^0.7.22",
    "@stencil/router": "latest"
    "@stencil/dev-server": "latest",
    "@stencil/utils": "latest",
      "^.+\\.(ts|tsx)$": "<rootDir>/node_modules/@stencil/core/testing/jest.preprocessor.js"

**Comment by kensodemann** [comment]
This no longer appears to be an issue.

Created an app with the latest starter using `npm init stencil`

This is the result:

```
~/Projects/Ionic/my-app: cat /proc/version
Linux version 4.15.0-34-generic (buildd@lgw01-amd64-047) (gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)) #37-Ubuntu SMP Mon Aug 27 15:21:48 UTC 2018
~/Projects/Ionic/my-app: npm ls @stencil/core
@stencil/starter@0.0.1 /home/kensodemann/Projects/Ionic/my-app
└── @stencil/core@0.13.2 
```

If this is still an issue for you please let me know.
