### ISSUE TITLE
Does not run on latest LTS

### ISSUE THREAD

**Issue by chimon2000** [ionic-team/stencil-app-starter#5]
### Issue
When testing out this app with node v6.11.2, the build fails with an error message stating that you need the latest LTS version.  

### Resolution
This is only resolved by installing the **current** version.

**Comment by xenu256** [comment]
Builds ok for me, node 6.11.2, npm 3.10.10, Windows 10.

**Comment by jgw96** [comment]
@chimon2000 is this issue still happening for you?

**Comment by mohammedzamakhan** [comment]
Stills happen for me.

```
> @stencil/starter@0.0.1 dev /Users/Zama/Desktop/passion/stencil-starter
> sd concurrent "stencil build --dev --watch" "stencil-dev-server"

sh: sd: command not found
```

**Comment by xenu256** [comment]
Everything works fine, you should install dependencies, like with any other Node project:

```text
npm install
```

**Comment by mohammedzamakhan** [comment]
@xenu256 

Now after running `npm install -g sd`, I get

```
/Users/Zama/Desktop/passion/stencil-starter/node_modules/@stencil/core/dist/cli/util.js:5051
      console.error(util.chalk.red('ERR: Your Node.js version is ' + util.chalk.bold(process.version) + '. Please update to the latest Node LTS version.\n'));
```

**Comment by xenu256** [comment]
Not enough of information, I'd maybe suggest to try to re-install Node after some cleanup? I've just tried it, it works for me both Node 6.10 and 8.6:

```text
PS C:\Users\DXenu\box\stencil-starter> npm install -g sd
C:\Users\DXenu\AppData\Roaming\npm\s -> C:\Users\DXenu\AppData\Roaming\npm\node_modules\sd\bin\sd
+ sd@0.0.3
updated 1 package in 3.595s

PS C:\Users\DXenu\box\stencil-starter> node -v
v8.6.0
PS C:\Users\DXenu\box\stencil-starter> npm -v
5.3.0
PS C:\Users\DXenu\box\stencil-starter> npm run dev

> @stencil/starter@0.0.1 dev C:\Users\DXenu\box\stencil-starter
> sd concurrent "stencil build --dev --watch" "stencil-dev-server"

[55:39.4]  build, dev mode, started ...
[55:39.4]  compile started ...
[55:44.8]  compile finished in 5.41 s
[55:44.9]  bundle styles started ...
[55:45.0]  bundle modules started ...
[55:45.4]  bundle styles finished in 514 ms
[55:46.0]  bundle modules finished in 1.02 s
[55:47.2]  build finished, watching for changes... in 7.84 s
```

**Comment by mohammedzamakhan** [comment]
I had 6.10 node version, after changing to 8.6, it worked for me

**Comment by xenu256** [comment]
You've run npm install to update packages afetr switching to node 8?

**Comment by jgw96** [comment]
Hello all! As this seems like more of a support issue im gonna ask that you join our [Stencil worldwide](https://join.slack.com/t/stencil-worldwide/shared_invite/enQtMjQ2MzkyMTY0MTk0LTQ4ODgzYjFjNjdkNDY3YWVhMmNlMTljMWQxNTM3Yjg0ZTIyZTM1MmU2YWE5YzNjNzE1MmQ3ZTk2NjQ1YzM5ZDM) slack channel and ask about this issue on there. Thanks!
