### ISSUE TITLE
ES5 build doesn't work on IE11: attachShadow not supported

### ISSUE THREAD

**Issue by mmatczak** [ionic-team/stencil-app-starter#73]
After setting the `buildEs5` config's property either to `true` or to `prod` and executing either `npm start` or `npm run build,` the `www` output target does not work on IE11. It prints: Object doesn't support property or method 'attachShadow'

I opened this issue also in the [Stencil repo](https://github.com/ionic-team/stencil/issues/2684) as I was not sure which repo is the right one.

**Comment by rwaskiewicz** [comment]
I'm going to close this issue, as it seems that the issue was resolved with [this comment in the issue linked above](https://github.com/ionic-team/stencil/issues/2684#issuecomment-729118986). However, if this is still an issue, please feel free to open a new issue in this repo
