### ISSUE TITLE
request: Test example

### ISSUE THREAD

**Issue by vvakame** [ionic-team/stencil-app-starter#9]
I think newbies are also interested in writing tests. 😉

**Comment by deividfortuna** [comment]
I totally agree

**Comment by Hotell** [comment]
I guess this can be closed right ? 
https://github.com/ionic-team/stencil-app-starter/blob/master/src/components/my-name/my-name.spec.ts

**Comment by kensodemann** [comment]
I am still in the process of writing documentation and a blog post describing it, but yes, I think this an be closed.
